"""Frozen oracle-derived KAT vectors (review 00003 H6).

The live differential suite (``tests/test_differential.py``) is the primary
correctness evidence for radices without published NIST vectors, but it
depends on ``ubiq-security-fpe`` -- a deprecated, unmaintained package.  The
day it stops installing, that evidence goes dark.

This module is the durability layer.  ``tests/vectors/oracle_kat_frozen.json``
holds known-answer vectors **generated by the oracle** (see
``tests/_oracle/generate_kat.py``), with a provenance header recording the
oracle version and generation date.  These tests run with no oracle
dependency at all.

This does not violate the no-self-authored-vectors rule: every expected
value was produced by the independent implementation, never by ``fpr-ff1``.
"""

import json
import pathlib
from typing import Any

from fpr_ff1 import FF1

_KAT_PATH = pathlib.Path(__file__).parent / "vectors" / "oracle_kat_frozen.json"

#: The radices the live differential suite covers.  10 and 36 also have NIST
#: vectors; the rest have none, which is exactly why their frozen evidence
#: matters most.
_ORACLE_RADICES = {2, 10, 16, 32, 36, 62, 256, 2**16 - 1}


def _load_kat() -> dict[str, Any]:
    # encoding="utf-8" is load-bearing: the file contains non-BMP alphabet
    # characters written as UTF-8, and on Windows (Python < 3.15) a bare
    # open() uses the locale codec (cp1252) and raises UnicodeDecodeError.
    with _KAT_PATH.open(encoding="utf-8") as handle:
        data: dict[str, Any] = json.load(handle)
    return data


def test_frozen_kat_provenance_is_recorded() -> None:
    """The frozen file must carry its provenance header.

    Without the oracle version and generation date the file is just a list
    of numbers; with them it is auditable evidence.
    """
    provenance = _load_kat()["provenance"]
    assert provenance["source"] == "ubiq-security-fpe (independent FF1 implementation)"
    assert provenance["oracle_version"] == "2.0.1.1"
    assert provenance["generator"] == "tests/_oracle/generate_kat.py"
    assert "generated_at" in provenance


def test_frozen_kat_covers_all_oracle_radices() -> None:
    """Every radix the live differential suite covers must be frozen too."""
    vectors = _load_kat()["vectors"]
    covered = {vector["radix"] for vector in vectors}
    assert covered == _ORACLE_RADICES


def test_frozen_kat_reaches_s_expansion_branch() -> None:
    """The frozen set must include ``d > 16`` cases for every radix.

    No NIST sample reaches the S-expansion; if the frozen vectors did not
    either, they would be blind to exactly the branch that once carried a
    real defect.
    """
    for vector in _load_kat()["vectors"]:
        radix = vector["radix"]
        n = len(vector["plaintext"])
        v = n - n // 2
        b = ((radix**v - 1).bit_length() + 7) // 8
        d = 4 * ((b + 3) // 4) + 4
        if d > 16:
            return
    raise AssertionError("no frozen vector reaches the S-expansion branch")


def test_frozen_kat_vectors_reproduce() -> None:
    """This implementation must reproduce every frozen oracle-derived vector.

    The expected values come from the independent implementation, so a
    failure here means this package deviated from the oracle's behaviour --
    the same claim the live tests make, durable against the oracle one day
    being uninstallable.
    """
    for vector in _load_kat()["vectors"]:
        ff1 = FF1(
            key=bytes.fromhex(vector["key_hex"]),
            radix=vector["radix"],
            alphabet=vector["alphabet"],
            tweak=bytes.fromhex(vector["tweak_hex"]),
        )
        assert ff1.encrypt(vector["plaintext"]) == vector["ciphertext"], (
            f"frozen KAT mismatch at radix {vector['radix']}, plaintext {vector['plaintext']!r}"
        )
        assert ff1.decrypt(vector["ciphertext"]) == vector["plaintext"]
